[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --include=dev --no-optional --cache=/tmp/.npm-cache || npm install --include=dev --no-optional --cache=/tmp/.npm-cache"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
