[phases.install]
cmds = ["echo '--- DEBUG package.json ---'", "cat package.json", "echo '--- DEBUG ls ---'", "ls -la", "npm cache clean --force", "npm install"]

[phases.build]
cmds = ["npm run build"]
