[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install --include=dev --no-audit --no-fund --cache=/tmp/.npm-cache"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_ENGINE_STRICT = "false"
